FROM alpine:3.22

ENV \
   TERM=xterm-color \
   TZ=Europe/Riga \
   PATH=${PATH}:/apache-maven-3.9.11/bin

RUN \
   apk add --update --no-cache ca-certificates curl git openjdk21-jdk tzdata && \
   ln -s /usr/share/zoneinfo/${TZ} /etc/localtime

RUN \
   curl -o /tmp/maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12-bin.tar.gz && \
   ( echo "0a1be79f02466533fc1a80abbef8796e4f737c46c6574ede5658b110899942a94db634477dfd3745501c80aef9aac0d4f841d38574373f7e2d24cce89d694f70  /tmp/maven.tar.gz" | sha512sum -c - ) && \
   tar -xvf /tmp/maven.tar.gz -C / && \
   rm /tmp/maven.tar.gz

WORKDIR /build
