FROM alpine:3.23

ENV \
   TERM=xterm-color \
   TZ=Europe/Riga \
   PATH=${PATH}:/apache-maven-3.9.15/bin

RUN \
   apk add --update --no-cache ca-certificates curl git openjdk17-jdk tzdata && \
   ln -s /usr/share/zoneinfo/${TZ} /etc/localtime

ADD files/apache-maven-3.9.15-bin.tar.gz /

WORKDIR /build
